
version: '3.7'

services:

  # https://github.com/SeleniumHQ/docker-selenium
  chrome:
    image: selenium/standalone-chrome-debug:3.14.0-iron
    container_name: chrome
    restart: always
    networks:
      - chrome
    volumes:
      - /dev/shm:/dev/shm
    expose:
      - 4444
    ports:
      - '5900:5900'

networks:
  chrome:
    name: chrome
